/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package promax.Forms;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import promax.Consulta.ConsultaCliente;
import promax.Consulta.ConsultaEmpleado;
import promax.Consulta.ConsultaFactura;
import promax.Consulta.ConsultaInventario;
import promax.Consulta.ConsultaProveedor;
import promax.Mant.MantCliente;
import promax.Mant.MantEmpleado;
import promax.Mant.MantFactura;
import promax.Mant.MantProducto;
import promax.Mant.MantProveedor;
import promax.Mant.MantUsuario;
import promax.Reportes.frmReportes;

/**
 *
 * @author aleja
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setSize(1200, 630);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mantenimiento = new javax.swing.JMenu();
        MantClientes = new javax.swing.JMenuItem();
        MantEmpleados = new javax.swing.JMenuItem();
        MantProductos = new javax.swing.JMenuItem();
        MantProveedor = new javax.swing.JMenuItem();
        MantFacturas = new javax.swing.JMenuItem();
        MantUsuarios = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        ConClientes = new javax.swing.JMenuItem();
        ConEmpleados = new javax.swing.JMenuItem();
        ConInventario = new javax.swing.JMenuItem();
        ConProveedor = new javax.swing.JMenuItem();
        ConDetFactura = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        Informes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1300, 630));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/promax/Imgs/Promax1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Technique BRK", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA DE FACTURACION");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(400, 400, 400))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        Mantenimiento.setBorder(null);
        Mantenimiento.setText("Mantenimiento");
        Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        MantClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantClientes.setText("Clientes");
        MantClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantClientesActionPerformed(evt);
            }
        });
        Mantenimiento.add(MantClientes);

        MantEmpleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantEmpleados.setText("Empleados");
        MantEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantEmpleadosActionPerformed(evt);
            }
        });
        Mantenimiento.add(MantEmpleados);

        MantProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantProductos.setText("Productos");
        MantProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantProductosActionPerformed(evt);
            }
        });
        Mantenimiento.add(MantProductos);

        MantProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantProveedor.setText("Proveedores");
        MantProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantProveedorActionPerformed(evt);
            }
        });
        Mantenimiento.add(MantProveedor);

        MantFacturas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantFacturas.setText("Facturas");
        MantFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantFacturasActionPerformed(evt);
            }
        });
        Mantenimiento.add(MantFacturas);

        MantUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantUsuarios.setText("Usuarios");
        MantUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantUsuariosActionPerformed(evt);
            }
        });
        Mantenimiento.add(MantUsuarios);

        jMenuBar1.add(Mantenimiento);

        Consultas.setBorder(null);
        Consultas.setText("Consultas");
        Consultas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ConClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConClientes.setText("Clientes");
        ConClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConClientesActionPerformed(evt);
            }
        });
        Consultas.add(ConClientes);

        ConEmpleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConEmpleados.setText("Empleados");
        ConEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConEmpleadosActionPerformed(evt);
            }
        });
        Consultas.add(ConEmpleados);

        ConInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConInventario.setText("Inventario");
        ConInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConInventarioActionPerformed(evt);
            }
        });
        Consultas.add(ConInventario);

        ConProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConProveedor.setText("Proveedores");
        ConProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConProveedorActionPerformed(evt);
            }
        });
        Consultas.add(ConProveedor);

        ConDetFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConDetFactura.setText("Detalle Fact");
        ConDetFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConDetFacturaActionPerformed(evt);
            }
        });
        Consultas.add(ConDetFactura);

        jMenuBar1.add(Consultas);

        Reportes.setBorder(null);
        Reportes.setText("Reportes");
        Reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Informes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Informes.setText("Informes");
        Informes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformesActionPerformed(evt);
            }
        });
        Reportes.add(Informes);

        jMenuBar1.add(Reportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MantClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantClientesActionPerformed
        MantCliente mc = new MantCliente();
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantClientesActionPerformed

    private void MantProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantProductosActionPerformed
        MantProducto mp = new MantProducto();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantProductosActionPerformed

    private void MantEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantEmpleadosActionPerformed
        MantEmpleado me = new MantEmpleado();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantEmpleadosActionPerformed

    private void MantProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantProveedorActionPerformed
        MantProveedor mp = new MantProveedor();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantProveedorActionPerformed

    private void MantFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantFacturasActionPerformed
        MantFactura mf = new MantFactura();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantFacturasActionPerformed

    private void ConClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConClientesActionPerformed
        ConsultaCliente cc = new ConsultaCliente();
        cc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConClientesActionPerformed

    private void ConEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConEmpleadosActionPerformed
        ConsultaEmpleado ce = new ConsultaEmpleado();
        ce.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConEmpleadosActionPerformed

    private void ConInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConInventarioActionPerformed
        ConsultaInventario ci = new ConsultaInventario();
        ci.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConInventarioActionPerformed

    private void ConProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConProveedorActionPerformed
        ConsultaProveedor cp = new ConsultaProveedor();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConProveedorActionPerformed

    private void ConDetFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConDetFacturaActionPerformed
        ConsultaFactura cf = new ConsultaFactura();
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConDetFacturaActionPerformed

    private void MantUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantUsuariosActionPerformed
        MantUsuario mu = new MantUsuario();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantUsuariosActionPerformed

    private void InformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformesActionPerformed
        frmReportes fr = new frmReportes();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InformesActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int rs = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?","Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(rs == 0){
            this.dispose();
        }
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConClientes;
    private javax.swing.JMenuItem ConDetFactura;
    private javax.swing.JMenuItem ConEmpleados;
    private javax.swing.JMenuItem ConInventario;
    private javax.swing.JMenuItem ConProveedor;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenuItem Informes;
    private javax.swing.JMenuItem MantClientes;
    private javax.swing.JMenuItem MantEmpleados;
    private javax.swing.JMenuItem MantFacturas;
    private javax.swing.JMenuItem MantProductos;
    private javax.swing.JMenuItem MantProveedor;
    private javax.swing.JMenuItem MantUsuarios;
    private javax.swing.JMenu Mantenimiento;
    private javax.swing.JMenu Reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
